version: "2.1"

services:
  iotbrokerservice:
    image: ${REPOSITORY}/onesaitplatform/iotbroker:${MODULE_TAG}
    container_name: iotbroker
    environment:
      - KAFKAENABLED="false"
      - SERVER_NAME="localhost"
      - REALTIMEDBUSEAUTH=false
    stdin_open: true
    networks:
      - op_data_datanetwork
    external_links:
      - configdb
      - schedulerdb
      - routerservice
      - realtimedb
networks:
  op_data_datanetwork:
    external: true
