version: "2.1"

services:
  flowengineservice:
    container_name: flowengine
    image: ${REPOSITORY}/onesaitplatform/flowengine:${MODULE_TAG}
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - PROTOCOL=${PROTOCOL}
      - REALTIMEDBUSEAUTH=false
    external_links:
      - quasar
      - configdb
      - routerservice
      - realtimedb
    networks:
      - op_data_datanetwork
networks:
  op_data_datanetwork:
    external: true
