version: "2.1"

services:
  zeppelin:
    networks:
      - op_data_datanetwork
    container_name: zeppelin
    image: ${REPOSITORY}/onesaitplatform/notebook:${MODULE_TAG}
networks:
  op_data_datanetwork:
    external: true
