version: "2.1"

services:
  devicesimulator:
    container_name: devicesimulator
    image: ${REPOSITORY}/onesaitplatform/devicesimulator:${MODULE_TAG}
    environment:
     - SERVER_NAME=${SERVER_NAME}
     - REALTIMEDBUSEAUTH=false
    stdin_open: true
    external_links:
     - routerservice
     - realtimedb
    networks:
    - op_data_datanetwork
networks:
  op_data_datanetwork:
    external: true
