version: "2.1"

services:
  apimanagerservice:
    container_name: apimanagerservice
    image: ${REPOSITORY}/onesaitplatform/apimanager:${MODULE_TAG}
    environment:
     - SERVER_NAME=localhost
     - REALTIMEDBUSEAUTH=false
    stdin_open: true
    external_links:
     - configdb
     - routerservice
     - cacheservice
     - realtimedb
    networks:
    - op_data_datanetwork
networks:
  op_data_datanetwork:
    external: true
