version: "2.1"

services:
  cacheservice:
    container_name: cacheserver
    environment:
      - REALTIMEDBUSEAUTH=false    
    networks:
      - op_data_datanetwork
    image: ${REPOSITORY}/onesaitplatform/cacheservice:${MODULE_TAG}
    external_links:
      - controlpanelservice
networks:
  op_data_datanetwork:
    external: true
