version: "2.1"

services:
  oauthservice:
    image: ${REPOSITORY}/onesaitplatform/oauthserver:${MODULE_TAG}
    container_name: oauthservice  
    ports:
      - "21000:21000"
    environment:
      - REALTIMEDBUSEAUTH=false 
      - SERVER_NAME=${SERVER_NAME}      
    networks:
      - op_data_datanetwork
    external_links:
      - configdb
networks:
  op_data_datanetwork:
    external: true
