version: "2.1"

services:
  rules-engine-service:
    image: ${REPOSITORY}/onesaitplatform/rules-engine:${MODULE_TAG}
    container_name: rules-engine-service   
    environment:
      - REALTIMEDBUSEAUTH=false          
    networks:
      - op_data_datanetwork
    ports:
     - "20200:20200"
    external_links:
     - configdb
     - realtimedb 
networks:
  op_data_datanetwork:
    external: true
