version: "2.1"

services:
  routerservice:
    container_name: router
    networks:
      - op_data_datanetwork
    image: ${REPOSITORY}/onesaitplatform/router:${MODULE_TAG}
    environment:
      - SERVER_NAME="localhost"
      - REALTIMEDBUSEAUTH=false
networks:
  op_data_datanetwork:
    external: true
