version: "2.1"

services:         
  controlpanelservice:
    image: ${REPOSITORY}/onesaitplatform/controlpanel:${MODULE_TAG}
    container_name: controlpanelservice 
    environment:
      - REALTIMEDBUSEAUTH=false 
      - SERVER_NAME=${SERVER_NAME}
      # If you deploy in a server over https ssl comment the following line (always uncomment by default). Change proxyurl port if using a different one (see nging.conf - server - listen)
      #- ONESAIT_PROPERTIES={"onesaitplatform":{"secure.cookie":false,"flowengine":{"services":{"proxyurl":"${PROTOCOL}://${SERVERNAME}/nodered/"}},"notebook":{"url":"${PROTOCOL}://${SERVERNAME}/controlpanel/notebooks/app/"}}}
      - ONESAIT_PROPERTIES={"onesaitplatform":{"secure.cookie":false,"flowengine":{"services":{"proxyurl":"${PROTOCOL}://${SERVER_NAME}/nodered/"}},"notebook":{"url":"${PROTOCOL}://${SERVER_NAME}/controlpanel/notebooks/app/"}}}
    networks:
     - op_data_datanetwork
    ports:
     - "18000:18000"
    volumes:
     - ${CP_VOLUME_WEB_PROJECTS}:/usr/local/webprojects:rw
    external_links:
     - configdb
     - realtimedb 
networks:
  op_data_datanetwork:
    external: true
