version: "2.1"

services:         
  controlpanelservice:
    image: ${REPOSITORY}/onesaitplatform/controlpanel:${MODULE_TAG}
    container_name: controlpanelservice 
    environment:
      - REALTIMEDBUSEAUTH=false 
      # If you deploy in a server over https ssl comment the following line (always uncomment by default). Change proxyurl port if using a different one (see nging.conf - server - listen)
      #- ONESAIT_PROPERTIES={"onesaitplatform":{"secure.cookie":false,"flowengine":{"services":{"proxyurl":"${PROTOCOL}://${SERVERNAME}/nodered/"}},"notebook":{"url":"${PROTOCOL}://${SERVERNAME}/controlpanel/notebooks/app/"}}}
      - ONESAIT_PROPERTIES={"onesaitplatform":{"secure.cookie":false,"flowengine":{"services":{"proxyurl":"${PROTOCOL}://${SERVERNAME}/nodered/"}},"notebook":{"url":"${PROTOCOL}://${SERVERNAME}/controlpanel/notebooks/app/"}}}
    networks:
      - op_data_datanetwork
    ports:
     - "18000:18000"
    external_links:
     - configdb
     - schedulerdb
     - realtimedb 
    volumes:
     - ${CP_VOLUME_WEB_PROJECTS}:/usr/local/webprojects:rw
networks:
  op_data_datanetwork:
    external: true
