version: "2.1"

services:
  configinitinstance:
    image: ${REPOSITORY}/onesaitplatform/configinit:${MODULE_TAG}
    container_name: configinitservice    
    environment:
      - REALTIMEDBUSEAUTH=false
      - SERVER_NAME=${SERVER_NAME}
      - LOADELASTICDB=false
      - LOADMONGODB=false
      - UPDATE_MODE_MULTITENANT=false
    networks:
      - op_data_datanetwork
    external_links:
      - configdb
      - realtimedb 
networks:
  op_data_datanetwork:
    external: true
