version: "2.1"

services:
  realtimedb:
    image: ${REPOSITORY}/onesaitplatform/realtimedb:${MONGO_TAG}
    container_name: realtimedb
    networks:
      - datanetwork
    ports:
      - "27017:27017"
    volumes:
      - ${REALTIME_VOLUME}:/data/db      
  configdb:
    image: ${REPOSITORY}/onesaitplatform/configdb:${PERSISTENCE_TAG}
    container_name: configdb
    networks:
      - datanetwork
    ports:
      - "3306:3306"
    volumes:
      - ${CONFIGDB_VOLUME}:/var/lib/mysql                 
  quasar:
    image: ${REPOSITORY}/onesaitplatform/quasar:${QUASAR_TAG}
    container_name: quasar
    networks:
     - datanetwork
    ports:
     - "18200:10800"
    environment:
     - REALTIMEDB=realtimedb 
    depends_on:
     - "realtimedb"
    restart: on-failure       
networks:
  datanetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
