version: "2.1"

services:
  realtimedb:
    image: ${REPOSITORY}/onesaitplatform/realtimedb:${MONGO_TAG}
    container_name: realtimedb
    networks:
      - datanetwork
    ports:
      - "27017:27017"
    volumes:
      - ${REALTIME_VOLUME}:/data/db      
  configdb:
    image: ${REPOSITORY}/onesaitplatform/configdb:${PERSISTENCE_TAG}
    container_name: configdb
    networks:
      - datanetwork
    ports:
      - "3306:3306"
    volumes:
      - ${CONFIGDB_VOLUME}:/var/lib/mysql                     
networks:
  datanetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
