version: "2.1"

services:
  monitoringuiservice:
    container_name: monitoringuiservice
    image: ${REPOSITORY}/onesaitplatform/monitoringui:${MODULE_TAG}
    environment:
     - SERVER_NAME=${SERVER_NAME}
     - REALTIMEDBUSEAUTH=false
    stdin_open: true
    external_links:
     - realtimedb
    networks:
    - op_data_datanetwork
networks:
  op_data_datanetwork:
    external: true
